- name: variables from inventory
  hosts: backend
  become: yes
  vars_files:
  - course.yaml
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"